---
- name: Add StatsD Group
  group:
    name: "{{ statsd_group }}"

- name: Add StatsD User
  user:
    name: "{{ statsd_user }}"
    group: "{{ statsd_group }}"
    shell: /bin/bash
    home: "{{ statsd_install_path }}"

- name: Create StatsD directory
  file:
    path: "{{ statsd_install_path }}"
    state: directory
    owner: "{{ statsd_user }}"
    group: "{{ statsd_group }}"