---
- name: Download StatsD and extract files
  unarchive:
    src: "{{ statsd_download_url }}"
    dest: "{{ statsd_install_path }}"
    remote_src: yes
    extra_opts: --strip-components=1
    creates: "{{ statsd_install_path }}/bin"

- name: Change file permission of StatsD installation directory
  file:
    dest: "{{ statsd_install_path }}"
    owner: "{{ statsd_user }}"
    group: "{{ statsd_group }}"
    recurse: yes